name: Pulimi - CI

on:
  push:
    branches:
      - main    

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Install node
        id: install-node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Install pnpm
        id: install-pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies
        id: install-dependencies
        run: |
          pnpm install

      - name: Configure AWS Credendials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Run Pulumi
        id: run-pulumi
        uses: pulumi/actions@v6
        with:
          command: up
          stack-name: FTR-iac/stg
          cloud-url: s3://ftr-pulumi-state-shandryll
        env:
          AWS-ACCESS-KEY-ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS-REGION: ${{ secrets.AWS_REGION }}
          AWS-SECRET-ACCESS-KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}